extends: eslint:recommended
parserOptions:
    ecmaVersion: 8
    ecmaFeatures:
        experimentalObjectRestSpread: true

env:
    es6: true
    node: true
    commonjs: true

rules:
    for-direction: error
    getter-return: error
    no-await-in-loop: error
    no-console: off
    no-extra-parens: [error, all, {conditionalAssign: false, enforceForArrowConditionals: false, nestedBinaryExpressions: false}]
    no-template-curly-in-string: error
    valid-jsdoc:
    - error
    -
        prefer:
            arg: param
            argument: param
            class: constructor
            return: returns
            virtual: abstract
        preferType:
            Boolean: boolean
            Number: number
            object: Object
            String: string
        requireReturn: false
    valid-typeof: [error, requireStringLiterals: true]

    accessor-pairs: error
    array-callback-return: error
    class-methods-use-this: error
    consistent-return: error
    curly: [error, multi-or-nest, consistent]
    default-case: [error, commentPattern: '^no default$']
    dot-location: [error, property]
    dot-notation: error
    eqeqeq: error
    guard-for-in: error
    no-caller: error
    no-div-regex: error
    no-else-return: [error, allowElseIf: false]
    no-empty-function: error
    no-eval: error
    no-extend-native: error
    no-extra-bind: error
    no-extra-label: error
    no-fallthrough: [error, commentPattern: '^ falls through$']
    no-floating-decimal: error
    no-implied-eval: error
    no-invalid-this: error
    no-iterator: error
    no-lone-blocks: error
    no-loop-func: error
    no-multi-spaces: error
    no-multi-str: error
    no-new: error
    no-new-wrappers: error
    no-octal: error
    no-octal-escape: error
    no-proto: error
    no-return-assign: error
    no-return-await: error
    no-self-compare: error
    no-sequences: error
    no-throw-literal: error
    no-unmodified-loop-condition: error
    no-unused-expressions: error
    no-unused-labels: error
    no-useless-call: error
    no-useless-concat: error
    no-useless-escape: error
    no-useless-return: error
    no-void: error
    no-warning-comments: [error, {terms: [todo, fixme], location: start}]
    no-with: error
    prefer-promise-reject-errors: error
    radix: [error, as-needed]
    require-await: error
    wrap-iife: [error, inside]
    yoda: [error, never, exceptRange: true]

    strict: [error, global]

    init-declarations: error
    no-label-var: error
    no-shadow-restricted-names: error
    no-undef: [error, typeof: true]
    no-undef-init: error
    no-use-before-define: error
    global-require: error
    handle-callback-err: error
    no-buffer-constructor: error
    no-new-require: error
    no-path-concat: error
    no-sync: [error, allowAtRootLevel: true]

    array-bracket-newline: error
    array-bracket-spacing: error
    block-spacing: error
    brace-style: error
    camelcase: error
    comma-dangle: [error, always-multiline]
    comma-spacing: error
    comma-style: error
    computed-property-spacing: error
    consistent-this: [error, use-arrow-functions]
    eol-last: error
    func-call-spacing: error
    func-names: [error, never]
    func-style: error
    function-paren-newline: error
    implicit-arrow-linebreak: error
    indent: [error, tab, SwitchCase: 1]
    key-spacing: error
    keyword-spacing:
    - error
    - overrides:
        catch: {after: false}
        for: {after: false}
        if: {after: false}
        switch: {after: false}
        while: {after: false}
        with: {after: false}
        function: {after: false}
    line-comment-position: [error, {position: above, applyDefaultIgnorePatterns: false}]
    linebreak-style: error
    lines-around-comment: [error, {ignorePattern: 'falls through', beforeLineComment: true, allowBlockStart: true}]
    lines-between-class-members: error
    max-nested-callbacks: [error, 1]
    max-statements-per-line: error
    multiline-comment-style: error
    multiline-ternary: [error, never]
    new-cap: error
    new-parens: error
    newline-per-chained-call: error
    no-array-constructor: error
    no-inline-comments: error
    no-lonely-if: error
    no-mixed-operators: error
    no-multiple-empty-lines: [error, {max: 1, maxBOF: 0, maxEOF: 0}]
    no-negated-condition: error
    no-new-object: error
    no-trailing-spaces: error
    no-unneeded-ternary: error
    no-whitespace-before-property: error
    nonblock-statement-body-position: [error, below]
    object-curly-newline: [error, {multiline: true, consistent: true}]
    object-curly-spacing: error
    object-property-newline: error
    one-var: [error, never]
    operator-assignment: error
    operator-linebreak: [error, after]
    padded-blocks: [error, never]
    quote-props: [error, consistent-as-needed]
    quotes: [error, single, avoidEscape: true]
    semi: [error, always, omitLastInOneLineBlock: true]
    semi-spacing: error
    semi-style: error
    space-before-blocks: error
    space-before-function-paren: [error, {anonymous: never, named: never}]
    space-in-parens: error
    space-infix-ops: error
    space-unary-ops: [error, {words: true, nonwords: false}]
    spaced-comment: [error, always, block: {balanced: true}]
    switch-colon-spacing: error
    template-tag-spacing: error
    unicode-bom: [error, never]

    arrow-body-style: error
    arrow-parens: [error, as-needed]
    arrow-spacing: error
    generator-star-spacing: [error, {before: false, after: true, method: neither}]
    no-confusing-arrow: [error, allowParens: true]
    no-restricted-imports: [error, patterns: ['*']]
    no-useless-computed-key: error
    no-useless-constructor: error
    no-var: error
    object-shorthand: error
    prefer-arrow-callback: error
    prefer-const: error
    prefer-destructuring: [error, {array: true, object: true}, {enforceForRenamedProperties: false}]
    prefer-numeric-literals: error
    prefer-rest-params: error
    prefer-spread: error
    prefer-template: error
    rest-spread-spacing: error
    symbol-description: error
    template-curly-spacing: error
    yield-star-spacing: error
