version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9-stretch

    steps:
      - checkout
      - run:
          name: System information
          command: |
            echo "Node $(node -v)"
            echo "Yarn v$(yarn --version)"
      - run:
          name: update apt-repository
          command: sudo apt-get update; sudo apt-get upgrade
      - run:
          name: Installing libudev-dev
          command: sudo apt-get install build-essential libudev-dev
      - run:
          name: Installing pip
          command: sudo apt-get install python-pip
      - run:
          name: Installing platformio
          command: sudo pip install -U platformio
      - run:
          name: Install dependencies / build serial
          command: npm i
      - run:
          name: TestTest
          command: npm run test
