version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9-stretch

    steps:
      - checkout
      - run:
          name: System information
          command: |
            echo "Node $(node -v)"
            echo "Yarn v$(yarn --version)"
      - run:
          name: Installing dependecies
          command: |
            sudo apt-get update; sudo apt-get upgrade
            sudo apt-get install build-essential libudev-dev
            sudo apt-get install python3-pip
            sudo pip3 install -U platformio
      - run:
          name: Run npm install
          command: npm i
      - run:
          name: TestTest
          command: npm run test
