version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9-stretch

    steps:
      - checkout
      - run:
          name: System information
          command: |
            echo "Node $(node -v)"
            echo "Yarn v$(yarn --version)"
      - run:
          name: Install dependencies / build serial
          command: npm i
      - run:
          name: TestTest
          command: npm run test
