; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
description = Dualpanto Initialization Firmware

[protocol]
base_dir = ../utils/protocol
include_dir = ${protocol.base_dir}/include
src_dir = ${protocol.base_dir}/src
src_filter = +<../${protocol.src_dir}>

[env:esp32dev]
platform = espressif32@2.1.0
board = esp32dev
framework = arduino
build_flags =
    -I${protocol.include_dir}
    -D_GLIBCXX_USE_C99
    -DENABLE_FPS
    -g
    -frtti
    -mtext-section-literals
    #-DENABLE_CRASHDUMP
    #-DENABLE_PERFMON
    # use this while debugging
    # -Og -ggdb
build_unflags =
    # use this while debugging
    # -Os
src_filter =
    +<*>
    ${protocol.src_filter}
monitor_speed = 115200
lib_deps = 
	paulstoffregen/Encoder@^1.4.4
	tomstewart89/BasicLinearAlgebra@^5.1
